import { Router, Request, Response } from 'express';

const router = Router();

// POST /api/email/send
// Requires: npm install resend
router.post('/send', async (req: Request, res: Response) => {
  const { to, invoiceNumber, clientName, total, currency, dueDate, pdfBase64 } = req.body;

  try {
    const { Resend } = await import('resend');
    const resend = new Resend(process.env.RESEND_API_KEY);

    await resend.emails.send({
      from: process.env.FROM_EMAIL ?? 'invoices@yourdomain.com',
      to,
      subject: `Invoice ${invoiceNumber}`,
      html: `
        <div style="font-family:'Space Grotesk',sans-serif;background:#09090B;color:#F2F2F2;padding:40px;max-width:600px;margin:auto;border-radius:12px;border:1px solid #2C2932;">
          <h1 style="font-family:'Orbitron',sans-serif;color:#8248DE;font-size:22px;margin:0 0 8px;">ht-invoice</h1>
          <p style="color:#8A8691;font-size:12px;margin:0 0 32px;">🇭🇹 Made in Haiti</p>
          <p style="margin:0 0 8px;">Hello <strong>${clientName}</strong>,</p>
          <p style="margin:0 0 24px;color:#8A8691;">Please find attached your invoice <strong style="color:#F2F2F2;">${invoiceNumber}</strong>.</p>
          <div style="background:#1A1821;border-radius:10px;padding:24px;margin:0 0 24px;border:1px solid #2C2932;">
            <p style="margin:0 0 4px;color:#8A8691;font-size:12px;text-transform:uppercase;letter-spacing:0.1em;">Amount Due</p>
            <p style="margin:0 0 4px;font-size:32px;font-weight:700;color:#8248DE;">${currency} ${total}</p>
            <p style="margin:0;color:#8A8691;font-size:13px;">Due by ${dueDate}</p>
          </div>
          <p style="color:#8A8691;font-size:11px;margin:0;">Generated by <a href="https://github.com/YOUR_USERNAME/ht-invoice" style="color:#8248DE;">ht-invoice</a></p>
        </div>
      `,
      attachments: pdfBase64 ? [{
        filename: `${invoiceNumber}.pdf`,
        content: pdfBase64,
        contentType: 'application/pdf',
      }] : [],
    });

    res.json({ success: true });
  } catch (err: any) {
    console.error(err);
    res.status(500).json({ error: err?.message ?? 'Email failed. Make sure RESEND_API_KEY is set and resend is installed.' });
  }
});

export default router;
