import { Router, Request, Response } from 'express';

const router = Router();

// POST /api/pdf/generate
// Body: { invoice, client, settings }
// Requires: npm install pdfkit @types/pdfkit
router.post('/generate', async (req: Request, res: Response) => {
  try {
    // Dynamic import so server starts without pdfkit if not installed
    const PDFDocument = (await import('pdfkit')).default;
    const { invoice, client, settings } = req.body;

    const SYMBOLS: Record<string, string> = { HTG: 'G', USD: '$', EUR: '€' };
    const sym = SYMBOLS[invoice.currency] ?? invoice.currency;
    const fmt = (n: number) => `${sym} ${Number(n).toLocaleString('en', { minimumFractionDigits: 2 })}`;

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));

    await new Promise<void>((resolve, reject) => {
      doc.on('end', resolve);
      doc.on('error', reject);

      // Business header
      doc.fontSize(20).font('Helvetica-Bold').fillColor('#111').text(settings.businessName, 50, 50);
      doc.fontSize(9).font('Helvetica').fillColor('#666')
        .text(settings.businessEmail)
        .text(settings.businessPhone || '')
        .text(settings.businessAddress || '');

      // Invoice title
      doc.fontSize(26).font('Helvetica-Bold').fillColor('#8248DE')
        .text('INVOICE', 350, 50, { align: 'right', width: 195 });
      doc.fontSize(9).font('Helvetica').fillColor('#555')
        .text(`# ${invoice.number}`, 350, 85, { align: 'right', width: 195 })
        .text(`Date: ${invoice.issueDate}`, { align: 'right', width: 195 })
        .text(`Due: ${invoice.dueDate}`, { align: 'right', width: 195 });

      // Client block
      doc.moveDown(2).fillColor('#111').fontSize(11).font('Helvetica-Bold').text('Bill To:');
      doc.fontSize(9).font('Helvetica').fillColor('#333')
        .text(client?.name ?? '—')
        .text(client?.company ?? '')
        .text(client?.email ?? '')
        .text(client?.address ?? '');

      // Line items
      const tableTop = 255;
      doc.moveTo(50, tableTop).lineTo(545, tableTop).lineWidth(0.5).strokeColor('#ddd').stroke();
      doc.fontSize(8).font('Helvetica-Bold').fillColor('#888')
        .text('DESCRIPTION', 50, tableTop + 8)
        .text('QTY', 340, tableTop + 8, { width: 50, align: 'right' })
        .text('UNIT PRICE', 395, tableTop + 8, { width: 80, align: 'right' })
        .text('AMOUNT', 480, tableTop + 8, { width: 65, align: 'right' });

      let y = tableTop + 28;
      (invoice.lineItems || []).forEach((item: any) => {
        const amount = item.quantity * item.unitPrice;
        doc.fontSize(9).font('Helvetica').fillColor('#111')
          .text(item.description, 50, y, { width: 280 })
          .text(String(item.quantity), 340, y, { width: 50, align: 'right' })
          .text(fmt(item.unitPrice), 395, y, { width: 80, align: 'right' })
          .text(fmt(amount), 480, y, { width: 65, align: 'right' });
        y += 22;
      });

      // Totals
      doc.moveTo(350, y + 6).lineTo(545, y + 6).lineWidth(0.5).strokeColor('#ddd').stroke();
      y += 14;
      doc.fontSize(9).font('Helvetica').fillColor('#666')
        .text('Subtotal', 370, y, { width: 110, align: 'right' })
        .text(fmt(invoice.subtotal), 480, y, { width: 65, align: 'right' });
      y += 16;
      doc.text(`Tax (${invoice.taxRate}%)`, 370, y, { width: 110, align: 'right' })
        .text(fmt(invoice.taxAmount), 480, y, { width: 65, align: 'right' });
      y += 16;
      doc.font('Helvetica-Bold').fillColor('#111').fontSize(11)
        .text('TOTAL', 370, y, { width: 110, align: 'right' })
        .text(fmt(invoice.total), 480, y, { width: 65, align: 'right' });

      if (invoice.notes) {
        doc.moveDown(4).fontSize(8).font('Helvetica-Bold').fillColor('#888').text('NOTES');
        doc.font('Helvetica').fillColor('#333').text(invoice.notes);
      }

      doc.fontSize(7).fillColor('#bbb')
        .text('Generated by ht-invoice · github.com/YOUR_USERNAME/ht-invoice', 50, 780, { align: 'center', width: 495 });

      doc.end();
    });

    const buffer = Buffer.concat(chunks);
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${invoice.number}.pdf`);
    res.send(buffer);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'PDF generation failed. Make sure pdfkit is installed: npm install pdfkit @types/pdfkit' });
  }
});

export default router;
